name: Build

on:
  push:
    branches: [ "development" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24.1'
    - name: Prepare dependencies
      run: npm clean-install
    - name: Build
      run: npm run build
      env:
        CARGO_TERM_COLOR: always
    - name: Commit changes to main branch
      run: |
        git fetch
        git checkout --detach
        git reset --soft origin/main
        git checkout origin/main
        git reset
        git add --force www/* wrangler.toml README.md
        git commit --message="${{ github.event.head_commit.message }}"
        git push origin HEAD:main
      env:
        GIT_AUTHOR_NAME: ${{ github.event.head_commit.author.name }}
        GIT_AUTHOR_EMAIL: ${{ github.event.head_commit.author.email }}
        GIT_COMMITTER_NAME: github-actions[bot]
        GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
